#!/bin/bash

echo "🚀 GitHub Repository Setup for Navi.com Website"
echo "=============================================="
echo ""
echo "Step 1: Create a new repository on GitHub"
echo "- Go to https://github.com/new"
echo "- Repository name: navi-website"
echo "- Set to Public (required for free Netlify)"
echo "- Don't initialize with README"
echo "- Click 'Create repository'"
echo ""
echo "Step 2: After creating the repository, replace YOUR_USERNAME below and run:"
echo ""
echo "# Replace YOUR_USERNAME with your actual GitHub username"
echo "git remote add origin https://github.com/YOUR_USERNAME/navi-website.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "Step 3: Connect to Netlify"
echo "- Go to https://app.netlify.com"
echo "- Click 'New site from Git'"
echo "- Choose GitHub and authorize"
echo "- Select your navi-website repository"
echo "- Build settings will be auto-detected from netlify.toml"
echo "- Click 'Deploy site'"
echo ""
echo "✅ Your code is already committed and ready to push!"
echo "✅ netlify.toml configuration is ready"
echo "✅ Build process verified working"
